### ISSUE TITLE
Add support for struct arguments in dtrace probes

### ISSUE THREAD

**Issue by rodionovd** [rodionovd/cuckoo-osx-analyzer#34]
It would be nice to be able to see the contents of any structure, not just it's address.

---

Consider the following API:

``` c
typedef struct {
    int hash;
    const char *definition;
} entry_t;


char *copy_entry_definition(entry_t *entry, int len);
```

One should be able to describe `entry_t` type in the API definition (or somewhere globally) like so:

``` json
"entry_t" : [
    {"field_name": "hash",       "field_type": "int"},
    {"field_name": "definition", "field_type": "string"},
]
```

and receive a report similar to this from Cuckoo:

```
          API          |               Arguments                   |     Status
-----------------------|-------------------------------------------|------------
copy_entry_definition  | entry: {hash => 971, definition = "hey"}  | SUCCEED
                       |     n: 128                                |
```

**Comment by rodionovd** [comment]
WIP branch: [`struct-arguments`](https://github.com/rodionovd/cuckoo-osx-analyzer/tree/struct-arguments).  

---

In other news: I've decided to go with YAML for type definitions:  

``` yaml
foo_t:
    native: No
    struct:
        abc: "double *"
        hfa: "size_t"
        sss: "char *"

unsigned long long: &unsigned-long-long
    printf_specifier: "%llu"
    native: Yes

"void *": *unsigned-long-long
```

I _believe_ it's more human-readable and writable than JSON.
